name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      name: Checkout
      uses: actions/checkout@v3
      run: python -m pip install --upgrade pip
      run: pip install -r requirements.txt
