name: CI workflow
on:
  push:
    branches:
      - main
      - github_actions
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install --upgrade pip
        run: pip install -r requirements.txt
      - name: Lint 1
        run: flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Lint 2
        run: flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Nosetests
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
